from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def pct(v):
    return "--" if v is None else f"{100*v:.1f}\%"


def ci(entry):
    if not entry:
        return "--"
    return f"{100*entry['point']:.1f}\% [{100*entry['lo95']:.1f}, {100*entry['hi95']:.1f}]"


def esc(s):
    return str(s).replace("_", "\\_")


def main():
    p=argparse.ArgumentParser()
    p.add_argument("--analysis", default="results/analysis_summary.json")
    p.add_argument("--stage-a", default="results/stage_a_summary.json")
    p.add_argument("--out", default="paper/generated_results.tex")
    args=p.parse_args()

    analysis=json.loads((ROOT/args.analysis).read_text(encoding="utf-8"))
    stage_a=json.loads((ROOT/args.stage_a).read_text(encoding="utf-8"))

    models=sorted({
        key.split("|")[0]
        for key in analysis.get("primary_rq2_stage_b",{})
    })
    if not models:
        models=sorted({
            key.split("|")[1]
            for key in analysis.get("groups",{})
            if "|" in key
        })

    lines=[]
    lines.append("% AUTO-GENERATED by scripts/render_paper_assets.py. Do not hand-edit.")
    lines.append("\\subsection{Retrieval exposure (RQ1)}")
    lines.append(
        "Before generation, retrieval-only calibration showed a strong tier imbalance for a single inserted document. "
        "Table~\\ref{tab:stagea} reports Poison@$k$ at $k=5$; this calibration motivated the forced-exposure RQ2 design."
    )
    lines.append("\\begin{table}[t]")
    lines.append("\\caption{Retrieval exposure at $k=5$ before generation.}")
    lines.append("\\label{tab:stagea}")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lrrr}")
    lines.append("\\toprule")
    lines.append("Condition & Tier 1 & Tier 2 & Overall \\\\")
    lines.append("\\midrule")
    names=[
        ("1 plain poison", "stage_a_plain_1.jsonl"),
        ("3 poison documents", "stage_a_plain_3.jsonl"),
        ("1 vendor bulletin", "stage_a_bulletin_1.jsonl"),
    ]
    runs={Path(x["file"]).name:x for x in stage_a["runs"]}
    for label,fn in names:
        r=runs.get(fn,{})
        lines.append(
            f"{label} & {pct(r.get('tier_1',{}).get('poison_at_5'))} & "
            f"{pct(r.get('tier_2',{}).get('poison_at_5'))} & "
            f"{pct(r.get('tier_all',{}).get('poison_at_5'))} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")

    lines.append("\\subsection{Forced-exposure adoption (RQ2)}")
    lines.append(
        "To compare public-standard and asset-specific facts without retrieval-selection bias, "
        "Stage B fixes a five-passage context containing exactly one poisoned passage."
    )
    lines.append("\\begin{table*}[t]")
    lines.append("\\caption{Attacker-value adoption under forced exposure. Values are item-cluster bootstrap estimates with 95\% intervals.}")
    lines.append("\\label{tab:rq2}")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lrrrr}")
    lines.append("\\toprule")
    lines.append("Model & First/T1 & First/T2 & Last/T1 & Last/T2 \\\\")
    lines.append("\\midrule")
    for model in models:
        vals=[]
        for pos in ["FIRST","LAST"]:
            for tier in [1,2]:
                e=analysis.get("primary_rq2_stage_b",{}).get(f"{model}|STAGE_B_{pos}|T{tier}")
                if e:
                    vals.append(f"{100*e['adoption']:.1f}\% [{100*e['lo95']:.1f}, {100*e['hi95']:.1f}]")
                else:
                    vals.append("--")
        lines.append(f"{esc(model)} & " + " & ".join(vals) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table*}")

    lines.append("\\subsection{Defense comparison (RQ3)}")
    lines.append(
        "Table~\\ref{tab:rq3} reports the paired reduction in benchmark violation rate relative to the "
        "three-poison vanilla-RAG stress baseline. Positive $\\Delta$SVR indicates fewer out-of-range commitments."
    )
    lines.append("\\begin{table*}[t]")
    lines.append("\\caption{Paired reduction in benchmark violation rate under the three-poison stress condition.}")
    lines.append("\\label{tab:rq3}")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lrrrrr}")
    lines.append("\\toprule")
    lines.append("Model & D1 & D2 & D3@40\% & D3@70\% & D3@100\% \\\\")
    lines.append("\\midrule")
    defenses=["D1_P3","D2_P3","D3_P3_40","D3_P3_70","D3_P3_100"]
    for model in models:
        vals=[]
        for d in defenses:
            e=analysis.get("primary_rq3_delta_svr",{}).get(f"{model}|{d}")
            if e:
                vals.append(f"{100*e['delta_svr']:.1f}\% [{100*e['lo95']:.1f}, {100*e['hi95']:.1f}]")
            else:
                vals.append("--")
        lines.append(f"{esc(model)} & " + " & ".join(vals) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table*}")

    lines.append("\\subsection{Legitimate-conflict cost}")
    lines.append(
        "Because the system-of-record table is intentionally incomplete with respect to legitimate jurisdictional "
        "variants, D3 can flag a correct context-specific answer. The benign-conflict false-flag rate (BFFR) "
        "quantifies this cost."
    )
    lines.append("\\begin{table}[t]")
    lines.append("\\caption{D3 benign-conflict false-flag rate.}")
    lines.append("\\label{tab:bffr}")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lrrr}")
    lines.append("\\toprule")
    lines.append("Model & 40\% & 70\% & 100\% \\\\")
    lines.append("\\midrule")
    for model in models:
        vals=[]
        for cov in [40,70,100]:
            e=analysis.get("bffr",{}).get(f"{model}|D3_CONFLICT_{cov}")
            vals.append(pct(e.get("rate")) if e else "--")
        lines.append(f"{esc(model)} & " + " & ".join(vals) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")

    out=ROOT/args.out
    out.write_text("\n".join(lines)+"\n",encoding="utf-8")
    print(out)


if __name__=="__main__":
    main()
