from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def pct(v):
    return "--" if v is None else f"{100*v:.1f}\\%"


def range_pct(values):
    vals = [v for v in values if v is not None]
    if not vals:
        return "--"
    lo, hi = min(vals), max(vals)
    if abs(lo - hi) < 1e-12:
        return f"{100*lo:.1f}\\%"
    return f"{100*lo:.1f}--{100*hi:.1f}\\%"


def count_range(values):
    lo, hi = min(values), max(values)
    return str(lo) if lo == hi else f"{lo}--{hi}"


def interval_pct(entry):
    if not entry:
        return "--"
    return f"{100*entry['point']:.1f}\\% [{100*entry['lo95']:.1f}, {100*entry['hi95']:.1f}]"


def delta_pp(entry):
    if not entry:
        return "--"
    return (
        f"{100*entry['delta_bvr']:.1f} "
        f"[{100*entry['lo95']:.1f}, {100*entry['hi95']:.1f}]"
    )


def short_model(model: str) -> str:
    names = {
        "mistralai/mistral-small-3.2-24b-instruct": "Mistral Small 3.2",
        "qwen/qwen3-8b": "Qwen3-8B",
        "openai/gpt-5.6-luna": "GPT-5.6 Luna",
    }
    return names.get(model, model.replace("_", "\\_"))


def read_jsonl(path: Path):
    return [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--analysis", default="results/analysis_summary.json")
    p.add_argument("--stage-a", default="results/stage_a_summary.json")
    p.add_argument("--out", default="paper/generated_results.tex")
    args = p.parse_args()

    analysis = json.loads((ROOT / args.analysis).read_text(encoding="utf-8"))
    stage_a = json.loads((ROOT / args.stage_a).read_text(encoding="utf-8"))

    preferred = [
        "mistralai/mistral-small-3.2-24b-instruct",
        "qwen/qwen3-8b",
        "openai/gpt-5.6-luna",
    ]
    models = [
        m for m in preferred
        if f"B1|{m}|T1" in analysis.get("groups", {})
    ]

    def group(condition, model, tier):
        return analysis["groups"][f"{condition}|{model}|T{tier}"]

    def across(condition, tier, metric):
        return [group(condition, m, tier).get(metric) for m in models]

    runs = {Path(x["file"]).name: x for x in stage_a["runs"]}

    # Structural SoR counts, kept data-driven rather than hand-coded.
    poisonable = (
        read_jsonl(ROOT / "benchmark/items/tier1_public.jsonl")
        + read_jsonl(ROOT / "benchmark/items/tier2_assets.jsonl")
    )
    tier3 = read_jsonl(ROOT / "benchmark/items/tier3_conflicts.jsonl")
    record_obj = json.loads(
        (ROOT / "benchmark/system_of_record/validation_table.json").read_text(encoding="utf-8")
    )
    record = {x["item_id"]: x for x in record_obj["entries"]}
    poisonable_record_matches = sum(
        record[x["item_id"]]["record_value"] == x["value"] for x in poisonable
    )
    tier3_generic = sum(
        record[x["item_id"]]["record_value"] != x["value"] for x in tier3
    )

    lines = []
    lines.append("% AUTO-GENERATED by scripts/render_paper_assets.py. Do not hand-edit.")

    clean_t2 = across("B1", 2, "CRR")
    clean_t1 = across("B1", 1, "CRR")
    lines.append(
        f"Clean-RAG CRR was {range_pct(clean_t2)} on Tier~2 "
        "(pre-specified threshold: 80\\%) and "
        f"{range_pct(clean_t1)} on Tier~1."
    )

    lines.append("\\subsection{Natural-retrieval behavior (RQ1)}")
    lines.append(
        "Table~\\ref{tab:natural} reports retrieval exposure and generation outcomes. "
        "Exposure is deterministic for the shared retriever; CRR and CAR are ranges across models."
    )
    lines.append("\\begin{table*}[t]")
    lines.append("\\caption{Natural-retrieval outcomes (\\%; $k=5$ unless noted).}")
    lines.append("\\label{tab:natural}")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{3.2pt}")
    lines.append("\\begin{tabular}{lrrrrrr}")
    lines.append("\\toprule")
    lines.append(" & \\multicolumn{3}{c}{Tier 1 (public)} & \\multicolumn{3}{c}{Tier 2 (asset)} \\\\")
    lines.append("Condition & Exp. & CRR & CAR & Exp. & CRR & CAR \\\\")
    lines.append("\\midrule")
    lines.append(
        f"Clean RAG & -- & {range_pct(across('B1', 1, 'CRR'))} & -- "
        f"& -- & {range_pct(across('B1', 2, 'CRR'))} & -- \\\\"
    )

    natural_specs = [
        ("1 poison", "B2_P1", "stage_a_plain_1.jsonl", "poison_at_5"),
        ("3 poisons", "B2_P3_STRESS", "stage_a_plain_3.jsonl", "poison_at_5"),
        ("1 bulletin", "B2_BULLETIN_P1", "stage_a_bulletin_1.jsonl", "poison_at_5"),
        ("1 poison, $k=2$", "B2_P1_K2", "stage_a_plain_1.jsonl", "poison_at_2"),
    ]
    for label, condition, stage_file, exposure_metric in natural_specs:
        r = runs[stage_file]
        lines.append(
            f"{label} & {pct(r['tier_1'][exposure_metric])} & "
            f"{range_pct(across(condition, 1, 'CRR'))} & "
            f"{range_pct(across(condition, 1, 'CAR'))} & "
            f"{pct(r['tier_2'][exposure_metric])} & "
            f"{range_pct(across(condition, 2, 'CRR'))} & "
            f"{range_pct(across(condition, 2, 'CAR'))} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table*}")

    one_correct = [
        analysis["natural_exposed"][f"{m}|B2_P1|T1"]["n_correct_exposed"] for m in models
    ]
    one_exposed = [
        analysis["natural_exposed"][f"{m}|B2_P1|T1"]["n_exposed"] for m in models
    ]
    k2_attacker = [
        analysis["natural_exposed"][f"{m}|B2_P1_K2|T1"]["n_attacker_exposed"] for m in models
    ]
    k2_exposed = [
        analysis["natural_exposed"][f"{m}|B2_P1_K2|T1"]["n_exposed"] for m in models
    ]
    wir_adopted = [analysis["wrong_in_range"][m]["n_adopted_exposed"] for m in models]
    wir_exposed = [analysis["wrong_in_range"][m]["n_exposed"] for m in models]
    lines.append(
        "At $k=5$, one poison was retrieved in 49 Tier~1 trials per model; only "
        f"{count_range(one_correct)} remained correct, while direct attacker adoption was 4.1\\% of exposed trials. "
        "Reducing retrieval depth to $k=2$ changed the evidence balance: all three models adopted the attacker value "
        f"in {count_range(k2_attacker)} of {count_range(k2_exposed)} exposed Tier~1 trials (CAR 34.6\\%). "
        "The wrong-but-in-range poison was copied in only "
        f"{count_range(wir_adopted)} of {count_range(wir_exposed)} exposed trials per model."
    )

    lines.append("\\subsection{Fixed-context exposure (RQ2)}")
    upper_t1 = analysis["primary_rq2_stage_b"][f"{models[0]}|STAGE_B_FIRST|T1"]["exact_hi95"]
    upper_t2 = analysis["primary_rq2_stage_b"][f"{models[0]}|STAGE_B_FIRST|T2"]["exact_hi95"]
    lines.append(
        "In the evidence-rich fixed context (three clean same-item supports, one distractor, one poison), "
        "attacker-value adoption and BVR were 0\\% in every model/tier/position cell. "
        f"With zero events, the exact 95\\% upper bounds on per-item adoption are {100*upper_t1:.1f}\\% "
        f"for Tier~1 ($n=35$) and {100*upper_t2:.1f}\\% for Tier~2 ($n=45$). "
        "Table~\\ref{tab:rq2} reports correct-answer retention."
    )
    lines.append("\\begin{table}[t]")
    lines.append("\\caption{Correct-answer rate under fixed exposure (\\%).}")
    lines.append("\\label{tab:rq2}")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lrrrr}")
    lines.append("\\toprule")
    lines.append("Model & First/T1 & First/T2 & Last/T1 & Last/T2 \\\\")
    lines.append("\\midrule")
    for model in models:
        vals = [
            group("STAGE_B_FIRST", model, 1)["CRR"],
            group("STAGE_B_FIRST", model, 2)["CRR"],
            group("STAGE_B_LAST", model, 1)["CRR"],
            group("STAGE_B_LAST", model, 2)["CRR"],
        ]
        lines.append(f"{short_model(model)} & " + " & ".join(pct(v) for v in vals) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append(
        "Every poison-last trial produced no numeric commitment. Because the base prompt explicitly permits "
        "\\texttt{VALUE: UNKNOWN} when evidence is inconsistent, this is a conflict-handling result rather than "
        "evidence of inherent poisoning robustness."
    )

    lines.append("\\subsection{Record-check accounting (RQ3)}")
    lines.append(
        "The locked primary comparison is D3 at 70\\% coverage versus D1 and D2. "
        "Table~\\ref{tab:rq3} reports paired BVR reduction in percentage points; positive values favor D3."
    )
    lines.append("\\begin{table*}[t]")
    lines.append("\\caption{Primary RQ3 comparison and violation counts. Brackets are 95\\% item-cluster bootstrap intervals.}")
    lines.append("\\label{tab:rq3}")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{3.2pt}")
    lines.append("\\begin{tabular}{lrrrr}")
    lines.append("\\toprule")
    lines.append("Model & D3@70 vs D1 (pp) & D3@70 vs D2 (pp) & B2 $\\rightarrow$ D3@70 & D3@100 \\\\")
    lines.append("\\midrule")
    for model in models:
        d1 = analysis["primary_rq3_locked"][f"{model}|D1_P3"]
        d2 = analysis["primary_rq3_locked"][f"{model}|D2_P3"]
        counts = analysis["rq3_counts"][model]
        b2v = counts["B2_P3_STRESS"]["n_violations"]
        d70v = counts["D3_P3_70"]["n_violations"]
        d100v = counts["D3_P3_100"]["n_violations"]
        lines.append(
            f"{short_model(model)} & {delta_pp(d1)} & {delta_pp(d2)} & "
            f"{b2v} $\\rightarrow$ {d70v} & {d100v} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table*}")

    qwen_d2 = analysis["secondary_rq3_vs_b2"]["qwen/qwen3-8b|D2_P3"]["delta_bvr"]
    max_discordant = max(
        x["b"] + x["c"] for x in analysis.get("mcnemar_primary", [])
    )
    pvals = [x["p_holm"] for x in analysis.get("mcnemar_primary", [])]
    lines.append(
        "Against vanilla poisoned RAG, D3@70 removed 6/7, 5/6, and 6/8 violating trials for "
        "Mistral, Qwen, and GPT-5.6 Luna, respectively, and full coverage removed all of them. "
        f"D2 increased Qwen BVR by {-100*qwen_d2:.1f} points relative to B2. "
        f"Only 5--8 trials violated per model and the primary McNemar comparisons had at most {max_discordant} "
        "discordant items; all six Holm-adjusted tests therefore remained non-significant "
        f"($p_{{\\mathrm{{Holm}}}}={min(pvals):.1f}$--{max(pvals):.1f}$). "
        "The defense comparisons are descriptive."
    )

    lines.append("\\subsection{Legitimate-conflict cost}")
    lines.append(
        f"The structured record equals the benchmark target for {poisonable_record_matches}/80 poisonable items, "
        f"but intentionally stores a generic alternative for {tier3_generic}/20 Tier~3 items. "
        "BFFR therefore measures a controlled record-scope gap and is conditioned on clean-RAG correctness."
    )
    lines.append("\\begin{table}[t]")
    lines.append("\\caption{Conditional benign-conflict false-flag rate (BFFR).}")
    lines.append("\\label{tab:bffr}")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lrrr}")
    lines.append("\\toprule")
    lines.append("Model & 40\\% & 70\\% & 100\\% \\\\")
    lines.append("\\midrule")
    for model in models:
        vals = []
        for cov in [40, 70, 100]:
            e = analysis["bffr"].get(f"{model}|D3_CONFLICT_{cov}")
            vals.append(pct(e["rate"]) if e else "--")
        lines.append(f"{short_model(model)} & " + " & ".join(vals) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append(
        "At 70\\% coverage, conditional BFFR was "
        f"{range_pct([analysis['bffr'][f'{m}|D3_CONFLICT_70']['rate'] for m in models])}; "
        "at full coverage it was "
        f"{range_pct([analysis['bffr'][f'{m}|D3_CONFLICT_100']['rate'] for m in models])}. "
        "The cost is therefore driven by record scope, not only by model behavior."
    )

    out = ROOT / args.out
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(out)


if __name__ == "__main__":
    main()
