from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def pct(v):
    return "--" if v is None else f"{100*v:.1f}\\%"


def interval(entry):
    if not entry:
        return "--"
    return f"{100*entry['point']:.1f}\\% [{100*entry['lo95']:.1f}, {100*entry['hi95']:.1f}]"


def short_model(model: str) -> str:
    names = {
        "mistralai/mistral-small-3.2-24b-instruct": "Mistral Small 3.2",
        "qwen/qwen3-8b": "Qwen3-8B",
        "openai/gpt-5.6-luna": "GPT-5.6 Luna",
    }
    return names.get(model, model.replace("_", "\\_"))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--analysis", default="results/analysis_summary.json")
    p.add_argument("--stage-a", default="results/stage_a_summary.json")
    p.add_argument("--out", default="paper/generated_results.tex")
    args = p.parse_args()

    analysis = json.loads((ROOT / args.analysis).read_text(encoding="utf-8"))
    stage_a = json.loads((ROOT / args.stage_a).read_text(encoding="utf-8"))

    present = {
        key.split("|")[0]
        for key in analysis.get("primary_rq2_stage_b", {})
    }
    preferred = [
        "mistralai/mistral-small-3.2-24b-instruct",
        "qwen/qwen3-8b",
        "openai/gpt-5.6-luna",
    ]
    models = [m for m in preferred if m in present]

    lines = []
    lines.append("% AUTO-GENERATED by scripts/render_paper_assets.py. Do not hand-edit.")
    lines.append("\\subsection{Retrieval exposure and natural-retrieval outcomes (RQ1)}")
    lines.append(
        "Retrieval-only calibration showed that one inserted document was exposed much more often "
        "for public-standard items than for fictional asset-specific items. "
        "Table~\\ref{tab:stagea} reports Poison@$k$ at $k=5$."
    )
    lines.append("\\begin{table}[t]")
    lines.append("\\caption{Poison exposure at $k=5$ in retrieval-only calibration.}")
    lines.append("\\label{tab:stagea}")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lrrr}")
    lines.append("\\toprule")
    lines.append("Condition & Tier 1 & Tier 2 & Overall \\\\")
    lines.append("\\midrule")
    names = [
        ("1 plain poison", "stage_a_plain_1.jsonl"),
        ("3 poison documents", "stage_a_plain_3.jsonl"),
        ("1 vendor bulletin", "stage_a_bulletin_1.jsonl"),
    ]
    runs = {Path(x["file"]).name: x for x in stage_a["runs"]}
    for label, fn in names:
        r = runs.get(fn, {})
        lines.append(
            f"{label} & {pct(r.get('tier_1', {}).get('poison_at_5'))} & "
            f"{pct(r.get('tier_2', {}).get('poison_at_5'))} & "
            f"{pct(r.get('tier_all', {}).get('poison_at_5'))} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")

    # Natural retrieval result sentence.
    one_t1 = []
    one_t2 = []
    three_t1 = []
    three_t2 = []
    for model in models:
        one_t1.append(analysis["groups"][f"B2_P1|{model}|T1"]["ASR"])
        one_t2.append(analysis["groups"][f"B2_P1|{model}|T2"]["ASR"])
        three_t1.append(analysis["groups"][f"B2_P3_STRESS|{model}|T1"]["ASR"])
        three_t2.append(analysis["groups"][f"B2_P3_STRESS|{model}|T2"]["ASR"])
    lines.append(
        "Despite this exposure, exact attacker-value adoption remained low. "
        f"With one poison, Tier~1 ASR was {100*min(one_t1):.1f}--{100*max(one_t1):.1f}\\% "
        f"and Tier~2 ASR was {100*min(one_t2):.1f}--{100*max(one_t2):.1f}\\%. "
        f"With three poisons, Tier~1 ASR was {100*min(three_t1):.1f}--{100*max(three_t1):.1f}\\% "
        f"and Tier~2 ASR was {100*min(three_t2):.1f}--{100*max(three_t2):.1f}\\% across models."
    )

    lines.append("\\subsection{Forced-exposure behavior (RQ2)}")
    lines.append(
        "Across all 12 model/tier/position cells, attacker-value adoption and benchmark-violation rate were both "
        "0\\%. The poison therefore changed conflict handling rather than causing direct adoption in this "
        "fixed five-passage control. Table~\\ref{tab:rq2} reports correct-answer retention."
    )
    lines.append("\\begin{table*}[t]")
    lines.append("\\caption{Correct-answer rate under forced exposure. Cluster-bootstrap 95\\% intervals are over items; attacker-value adoption was 0\\% in every cell.}")
    lines.append("\\label{tab:rq2}")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lrrrr}")
    lines.append("\\toprule")
    lines.append("Model & First/T1 & First/T2 & Last/T1 & Last/T2 \\\\")
    lines.append("\\midrule")
    for model in models:
        vals = []
        for pos in ["FIRST", "LAST"]:
            for tier in [1, 2]:
                key = f"STAGE_B_{pos}|{model}|T{tier}|CRR"
                vals.append(interval(analysis.get("intervals", {}).get(key)))
        lines.append(f"{short_model(model)} & " + " & ".join(vals) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table*}")
    lines.append(
        "Poison-last contexts produced 0\\% correct-answer retention for all three models and both tiers; "
        "responses instead declined to commit because the final passage contradicted the preceding majority. "
        "Poison-first retention varied substantially by model and tier, showing a position effect without attacker-value adoption."
    )

    lines.append("\\subsection{Defense comparison (RQ3)}")
    lines.append(
        "Table~\\ref{tab:rq3} reports the paired reduction in benchmark-violation rate relative to the "
        "three-poison vanilla-RAG stress baseline. Positive $\\Delta$SVR indicates fewer out-of-range commitments."
    )
    lines.append("\\begin{table*}[t]")
    lines.append("\\caption{Paired reduction in benchmark-violation rate under the three-poison stress condition.}")
    lines.append("\\label{tab:rq3}")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lrrrrr}")
    lines.append("\\toprule")
    lines.append("Model & D1 & D2 & D3@40\\% & D3@70\\% & D3@100\\% \\\\")
    lines.append("\\midrule")
    defenses = ["D1_P3", "D2_P3", "D3_P3_40", "D3_P3_70", "D3_P3_100"]
    for model in models:
        vals = []
        for d in defenses:
            e = analysis.get("primary_rq3_delta_svr", {}).get(f"{model}|{d}")
            if e:
                vals.append(
                    f"{100*e['delta_svr']:.1f}\\% [{100*e['lo95']:.1f}, {100*e['hi95']:.1f}]"
                )
            else:
                vals.append("--")
        lines.append(f"{short_model(model)} & " + " & ".join(vals) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table*}")
    lines.append(
        "At 70\\% record coverage, D3 reduced SVR by 3.1--3.8 percentage points across models; "
        "at 100\\% coverage the reduction was 3.8--5.0 points. D2 did not improve Mistral or GPT-5.6 Luna "
        "and increased Qwen SVR by 3.1 points. All planned Holm-adjusted McNemar tests were non-significant "
        "($p_{\\mathrm{Holm}}=1.0$), so the bootstrap effect-size intervals are interpreted descriptively."
    )

    lines.append("\\subsection{Legitimate-conflict cost}")
    lines.append(
        "D3 can reject a correct context-specific answer when the simplified structured record lacks the applicable "
        "jurisdictional or interconnection variant. BFFR is therefore computed only among Tier~3 trials for which "
        "clean RAG first returned the benchmark-correct answer."
    )
    lines.append("\\begin{table}[t]")
    lines.append("\\caption{Conditional benign-conflict false-flag rate (BFFR).}")
    lines.append("\\label{tab:bffr}")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lrrr}")
    lines.append("\\toprule")
    lines.append("Model & 40\\% & 70\\% & 100\\% \\\\")
    lines.append("\\midrule")
    for model in models:
        vals = []
        for cov in [40, 70, 100]:
            e = analysis.get("bffr", {}).get(f"{model}|D3_CONFLICT_{cov}")
            vals.append(pct(e.get("rate")) if e else "--")
        lines.append(f"{short_model(model)} & " + " & ".join(vals) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append(
        "The coverage benefit therefore has a clear cost: at 70\\% coverage BFFR was about 43.6--45.7\\%, "
        "and at full coverage it was about 64.1--65.7\\%."
    )

    out = ROOT / args.out
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(out)


if __name__ == "__main__":
    main()
